name: wordpress-lando
recipe: wordpress
config:
  webroot: .
services:
  database:
    type: mysql #type de DB
    portforward: 3307 #Port sur lequel on va écouter
    creds:
      user: root #Nom d'utilisateur de DB
      password: #Password de DB
      database: master #Nom de la DB
tooling:
  install:
    service: appserver
    description: "commande pour installer wordpress"
    cmd:
      - echo Installation Wordpress....
      - recipe php avec mysql config/install_wp.recipe php avec mysql